### PR TITLE
Add the Gitlab auth provider

### PR DESCRIPTION
**Pull request by tcitworld**
It requires an optional yiiauth/gitlab client.

Also added gitlab logo since it's not in ion logos

### CODE REVIEW

**Comment by tcitworld** [comment]
(also, I don't know Yii much, you're welcomed to extract strings)

**Comment by ganigeorgiev** [comment]
Thanks for the pull request. This weekend I'll try to review it in details and return you a feedback.

**Comment by Laul0** [comment]
#79

**Comment by ganigeorgiev** [comment]
@tcitworld Thanks again for the pull request. I've made some very minor modifications (mainly related to the UI) in the develop branch - https://github.com/ganigeorgiev/presentator/commit/09c5338f0a727cdac215b09f31a8df6a27007720.

Also I've opened a pull request to [yiiauth/gitlab repo](https://github.com/yiiauth/gitlab/pull/2) because of the php version requirement in the composer file. Once it is updated, I'll merge the develop branch into master and includes it in v1.11.0 release.

**Comment by tcitworld** [comment]
Looks really great, thanks !

**Pull request closed without merging**
