### PR TITLE
dockerizing dev-environment

### PR DESCRIPTION
**Pull request by der-On**
I'm trying to dockerize this.

So far I came to the point where I was able to use the installer to setup presentator in the docker environment but then this error came up:

```
 PHP User Error – yii\base\ErrorException
Exception 'yii\base\InvalidParamException' with message 'The file or directory to be published does not exist: /var/www/vendor/bower/jquery/dist'
```

I've lunched the docker containers and did a `composer install`.

To try this out yourself clone the branch and then:

```
docker-compose up
```

and then in another terminal but in the same directory

```
./docker/setup/00-setup.sh
```

Database credentials  within the docker dev environment are:
```
host: db
database: presentator
user: presentator
pass: presentator
```

### CODE REVIEW

**Comment by der-On** [comment]
Currently I find the entire installation process cumbersome and error prone.

Docker enabled applications should not require so many manual installation steps and rely on manually created config files. Instead already existing config files should make use of environment variables and provide usefull defaults.

Also the docs about how to migrate the presentator database are not clear.

**Comment by der-On** [comment]
The forced redirect to https also has to be fixed to work within a docker environment.

**Comment by der-On** [comment]
The goal of dockerizing here is to have a dockerized dev environment. The docker image should of course contain the stable release as you suggest.

**Comment by ganigeorgiev** [comment]
The above error seems to occur with the latest version of the composer asset plugin due to some changes related to the bower directory name.
Because the yii2 team suggests to use [asset-packagist](https://asset-packagist.org/) for managing npm/bower decencies with composer, I've pushed an update in the develop branch - https://github.com/ganigeorgiev/presentator/commit/2a57ae870e6bf0518d4559a04b84d912a7b95c11.

**Comment by der-On** [comment]
@ganigeorgiev thank you. I will merge develop. I was branching this off from master. I guess that was wrong anyway.

**Comment by der-On** [comment]
@ganigeorgiev I think now I've got it working. Also I get another Error now when trying to register

```
Database Exception – yii\db\Exception
SQLSTATE[HY000] [2002] No such file or directory
↵
Caused by: PDOException
SQLSTATE[HY000] [2002] No such file or directory

in /var/www/vendor/yiisoft/yii2/db/Connection.php at line 687
``` 

Running `php yii migrate` however works, so DB connection seems to be set up correctly.

**Comment by ganigeorgiev** [comment]
@der-On Thanks for the PR.

I haven't tested it yet, but probably the db error occurs because of unresolved environment variables (at work I've a similar issue and was related to the default apache security restrictions - https://stackoverflow.com/questions/23915066/why-is-getenv-only-returning-a-variable-when-run-from-the-terminal-not-via-we).

This weekend I'll have more time and I'll try to review it in more details and return you a feedback.

**Comment by der-On** [comment]
Thanks. Now things work nice. Using env variables was not working at all, which is a pitty.
I've added the setup script 21-fix-creds.sh to overwrite common/config/main-local.php with a version containing the correct DB credentials.

**Comment by der-On** [comment]
Where does the swiftmailer file transport writes out mails?

**Comment by ganigeorgiev** [comment]
@der-On Sorry for the late response.

Yesterday I tested your changes, but I encountered some permission issues and the vhosts didn't seems to work (could be specific to only my environment).
So I've made some minor modifications to your PR in a separate branch - https://github.com/ganigeorgiev/presentator/tree/dockerize.

The main changes are:
- using the offical php-apache as base image
- added adminer (db GUI) and nginx-proxy (reverse proxy for easier vhosts management/define only `127.0.0.1 adminer.local app.presentator.local api.presentator.local` in your hosts file/) to docker-compose
- modified docker setup scripts (`codecept`, `grunt`, `setup`, `run`)

Please let me know if you don't agree with the changes.

**Comment by der-On** [comment]
@ganigeorgiev I've already checked out the commits and find the changes very good. Thank you for the improvement!

**Comment by der-On** [comment]
I guess this PR can be closed then?

**Comment by ganigeorgiev** [comment]
@der-On The dockerize branch is merged in develop (will be available in master with v1.8.0 release).

Thanks again for your work.

**Pull request closed without merging**
